### ISSUE TITLE
Is this thread safe?

### ISSUE THREAD

**Issue by thsutton** [bitonic/sundown#1]
I haven't bothered to track it down yet but I've been seeing a problem which I suspect might be due to upskirt. I'm using upskirt in a Snap web app (basically a blog) like so:

```
markdownSplice :: (Monad m) => T.Text -> Splice m
markdownSplice text = do
  let bs = TE.encodeUtf8 text
  let html = renderHtml bs allExtensions noHtmlModes
  return $ case X.parseHTML "" html of
    Left _    -> []
    Right doc -> X.docContent doc
```

Basically it takes a Text value, runs it through upskirt, parses the result into an XmlHtml document (fragment) and returns that so it can be stitched into a page. This works, but subsequent requests will return different (incorrect) values with additional characters, etc. in the returned values. As I said, I haven't looked at this at all but thought I may as well ask: is upskirt safe to use in multithreaded threaded code?

**Comment by bitonic** [comment]
I don't see how multi threading should matter in this case, but I might easily be wrong.
So if I understand well, parsing the bytestring gives inconsistent results? As in, parsing the same ByteString twice will produce different output?
Could you give me an example?

**Comment by thsutton** [comment]
I've had a quick poke through markdown.c and it seems to have a few globals and static. I haven't looked under the covers at the Snap web server but I expect requests are being mapped onto multiple threads by the server or GHC I/O manager round-robin. In any case: I get different results when I hit the refresh button.

Here's three screenshots of the changing data: http://www.flickr.com/photos/thsutton/5726374196/. The first 4 posts are the first request, the next 3 are the second and the last 3 are third request. The different sizes are because I'm lazy, the data itself is unchanged.

**Comment by bitonic** [comment]
My bad, I'll look into it as soon as my exams are over. In the meantime, if you fix it, just issue a pull request.

I hacked that binding in a few hrs, something had to be wrong!

**Comment by thsutton** [comment]
I'll have a look but I think that the bug is in the design of the upskirt C code. It's them who're using global variables for parser state not you! :-)

**Comment by vmg** [comment]
Hey, this is not multi-threading error -- Sundown (formerly known as Upskirt) is fully thread-safe and has no global state whatsoever (I don't know where did you find any).

By the looks of it, it seems like there's an issue in the Haskell wrapping. Note that buffers in Sundown are not null-terminated, they have instead a length defined by the `size` attribute. This could be the source of the "extra characters" and wrong results you've been seeing.

Either way, I'd strongly advice not to wrap the `buffer` structure in Haskell, and instead do the same thing we do in Redcarpet and Misaka -- take and return raw strings when parsing. I'm afraid my Haskell-fu is not good enough to offer more advice, but I can tell you that this exact website (GitHub) uses Sundown to render hundreds of Markdown documents every minute, and we've never found a race condition.

**Comment by bitonic** [comment]
Hi tanoku,

The fact that buffer strings are not null terminated is most likely the cause of the problem (I am using a function that requires strings to be null terminated).

I don't understand your advice "take and return raw strings when parsing", because that's what I'm doing, in Haskell limits (Returning a C string directly would be stupid). ByteStrings are more or less equivalent to C strings (char vectors) and that's what I am returning.

What I'll do is simply get the ByteString taking the size into account.

Thanks for your help
